<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-27T00:59:01 BST" name="Suite" finished-at="2022-06-27T00:59:17 BST" duration-ms="15855">
    <groups>
    </groups>
    <test started-at="2022-06-27T00:59:01 BST" name="Validation Test" finished-at="2022-06-27T00:59:10 BST" duration-ms="9121">
      <class name="WebPage.ValidationTest">
        <test-method is-config="true" signature="initialize()[pri:0, instance:WebPage.ValidationTest@305f031]" started-at="2022-06-27T00:59:01 BST" name="initialize" finished-at="2022-06-27T00:59:09 BST" duration-ms="7780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="ValidatePage()[pri:0, instance:WebPage.ValidationTest@305f031]" started-at="2022-06-27T00:59:09 BST" name="ValidatePage" finished-at="2022-06-27T00:59:09 BST" duration-ms="101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidatePage -->
        <test-method signature="ValidatePageFooter()[pri:0, instance:WebPage.ValidationTest@305f031]" started-at="2022-06-27T00:59:09 BST" name="ValidatePageFooter" finished-at="2022-06-27T00:59:09 BST" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidatePageFooter -->
        <test-method is-config="true" signature="exit()[pri:0, instance:WebPage.ValidationTest@305f031]" started-at="2022-06-27T00:59:10 BST" name="exit" finished-at="2022-06-27T00:59:10 BST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- WebPage.ValidationTest -->
    </test> <!-- Validation Test -->
    <test started-at="2022-06-27T00:59:01 BST" name="Application Test" finished-at="2022-06-27T00:59:17 BST" duration-ms="15855">
      <class name="WebPage.ApplicationTest">
        <test-method is-config="true" signature="initialize()[pri:0, instance:WebPage.ApplicationTest@21d8bcbe]" started-at="2022-06-27T00:59:01 BST" name="initialize" finished-at="2022-06-27T00:59:09 BST" duration-ms="7692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="basePage(java.lang.String,java.lang.String)[pri:0, instance:WebPage.ApplicationTest@21d8bcbe]" started-at="2022-06-27T00:59:09 BST" name="basePage" data-provider="getData" finished-at="2022-06-27T00:59:12 BST" duration-ms="3612" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sruthi.c95@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8903479938]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at WebPage.ApplicationTest.basePage(ApplicationTest.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basePage -->
        <test-method signature="basePage(java.lang.String,java.lang.String)[pri:0, instance:WebPage.ApplicationTest@21d8bcbe]" started-at="2022-06-27T00:59:12 BST" name="basePage" data-provider="getData" finished-at="2022-06-27T00:59:16 BST" duration-ms="3930" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[gopusd@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sruthi123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at WebPage.ApplicationTest.basePage(ApplicationTest.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basePage -->
        <test-method is-config="true" signature="exit()[pri:0, instance:WebPage.ApplicationTest@21d8bcbe]" started-at="2022-06-27T00:59:17 BST" name="exit" finished-at="2022-06-27T00:59:17 BST" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- WebPage.ApplicationTest -->
    </test> <!-- Application Test -->
  </suite> <!-- Suite -->
</testng-results>
